import math
import time

// Please see "libraries/simplelib.sk" for the rest of the example
import "examples/libraries/simplelib.sk" as mylib

// debugging timer
let timer = time.startTimer() // returns timer's ID, starting from 0

mylib.fibonacci(10)

time.sleep(1)

print("Pi: " + str(math.PI)) // PI from the math lib inside the simplelib library
print("Now: " + str(time.format(time.now())))

let elapsed = time.stopTimer(0)
print("Test file took " + str(elapsed) + " seconds to run!")
