


// SK Programming Language

unknown myvar // same as let myvar = unknown
let number = 67
let version = 1.0
let interval = [0..1]
let scientific = 10e3

print("Hello, World!")

number = number + scientific

print(0*myvar)
print(number)
print(kind(number))
print(kind(str(number)))

print("This is my fav variable:" + " " + str(interval))
print("[-2..2] ^ 2 = " + str([-2..2] ^ 2))

print(42 % 2)

panic!

print("This shouldn't be printed out!")